services:
  api:
    volume:
      - ./wallet:/app/wallet
    enviroment:
      ORACLE_WALLET_PATH: /app/wallet
    build: .
    container_name: axioma_api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    restart: unless-stopped
